# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from verrpc import verrpc_pb2 as verrpc_dot_verrpc__pb2


class VersionerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetVersion = channel.unary_unary(
        '/verrpc.Versioner/GetVersion',
        request_serializer=verrpc_dot_verrpc__pb2.VersionRequest.SerializeToString,
        response_deserializer=verrpc_dot_verrpc__pb2.Version.FromString,
        )


class VersionerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetVersion(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VersionerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetVersion': grpc.unary_unary_rpc_method_handler(
          servicer.GetVersion,
          request_deserializer=verrpc_dot_verrpc__pb2.VersionRequest.FromString,
          response_serializer=verrpc_dot_verrpc__pb2.Version.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'verrpc.Versioner', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
